# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
cache: pip
group: deprecated-2017Q3
python:
  - 3.4.5
services:
  - docker
install:
  - ./travis-scripts/install.sh
script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      $(aws ecr get-login);
    fi
  - ./travis-scripts/build_assets.sh
  - ./travis-scripts/test.sh
  - ./travis-scripts/build_images.sh
after_success:
  - ./travis-scripts/deploy.sh
provider: releases
on:
  tags: true
